version: '3.7'

services:
  db:
    image: mariadb
    restart: always
    env_file:
      - db.env
    volumes:
      - db_data:/var/lib/mysql

  ts3server:
    image: teamspeak
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    depends_on:
      - db
    env_file:
      - teamspeak.env
    volumes:
      - server_data:/var/ts3server

  tsdns:
    image: teamspeak
    restart: always
    env_file:
      - .env
      - tsdns.env
    command: sh -c "echo $${TSDNS_HOST_ENTRIES} | sed s/,/\\n/g > /var/ts3server/tsdns_settings.ini && /opt/ts3server/tsdns/tsdnsserver"
    ports:
      - 41144:41144
    depends_on:
      - ts3server
    volumes:
      - tsdns_data:/var/ts3server

volumes:
  tsdns_data:
  server_data:
  db_data: