version: "3.7"

volumes:
  server_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${TS3_NFS_SERVER},${TS3_NFS_MOUNTOPTS:-rw,nolock}
      device: ${TS3_NFS_SERVER}:${TS3_NFS_MOUNT}

