version: "3.7"

services:
  ts3server:
    image: teamspeak:${TAG:-latest}
    restart: unless-stopped
    env_file:
      - ts3server.env
    volumes:
      - server_data:/var/ts3server

volumes:
  server_data:
