version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: teamspeak
      MYSQL_USER: teamspeak
      MYSQL_PASSWORD: teamspeak
    volumes:
      - db_data:/var/lib/mysql

  ts3server:
    image: teamspeak
    restart: always
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: teamspeak
      TS3SERVER_DB_PASSWORD: teamspeak
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    ports:
      - 2008:2008
      - 2010:2010/udp
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    depends_on:
      - db
    volumes:
      - server_data:/var/ts3server

  tsdns:
    image: teamspeak
    restart: always
    environment:
      TSDNS_HOST_ENTRIES: ${TSDNS_HOST_ENTRIES}
    command: sh -c "echo $${TSDNS_HOST_ENTRIES} | sed s/,/\\\\n/g > /var/ts3server/tsdns_settings.ini && /opt/ts3server/tsdns/tsdnsserver"
    ports:
      - 41144:41144
    depends_on:
      - ts3server
    volumes:
      - tsdns_data:/var/ts3server

volumes:
  db_data:
  server_data:
  tsdns_data: