version: "3.7"

services:
  jdownloader2:
    image: jlesage/jdownloader-2
    restart: unless-stopped
    env_file:
      - jdownloader2.env
    volumes:
      - jdownloader2_data:/config
      - downloads:/output

volumes:
  jdownloader2_data:
  downloads:
