version: '3'
services:
  pihole:
    image: pihole/pihole
    restart: unless-stopped
    env_file:
      - pihole.env
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "67:67/udp"
      - "8053:80/tcp"
    volumes:
      - pihole_data:/etc/pihole
      - dnsmasq_data:/etc/dnsmasq.d
      - /var/log/docker/pihole.log:/var/log/pihole.log
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1

volumes:
  pihole_data:
  dnsmasq_data:
