version: "3.7"

services:
  pihole:
    image: pihole/pihole
    restart: unless-stopped
    env_file:
      - pihole.env
    volumes:
      - pihole_data:/etc/pihole
      - dnsmasq_data:/etc/dnsmasq.d
    networks:
      net:

volumes:
  pihole_data:
  dnsmasq_data:

# this will create a network named pihole_net (for adding containers to this network like VPNs or X11VNC web gui applications)
networks:
  net: