version: "3.7"

services:
  pihole:
    labels:
      traefik.enable: true
      traefik.http.middlewares.pihole-https.redirectscheme.scheme: https
      traefik.http.routers.pihole-http.entrypoints: web
      traefik.http.routers.pihole-http.rule: "Host(`${SUBDOMAIN:-pihole}.${DOMAIN}`)"
      traefik.http.routers.pihole-http.middlewares: pihole-https@docker
      traefik.http.routers.pihole.entrypoints: web-secure
      traefik.http.routers.pihole.rule: "Host(`${SUBDOMAIN:-pihole}.${DOMAIN}`)"
      traefik.http.routers.pihole.tls: true
      traefik.http.routers.pihole.tls.certresolver: default
      traefik.http.routers.pihole.middlewares: secHeaders@file
      traefik.http.services.pihole.loadbalancer.server.port: 80
      traefik.http.services.pihole.loadbalancer.healthcheck.port: 80
    networks:
      traefik_net:

networks:
  traefik_net:
    external: true
