version: "3.7"

services:
  pihole:
    ports:
      - "${PIHOLE_DNS_PORT:-53}:53/udp"
      - "${PIHOLE_DNS_PORT:-53}:53/tcp"
      - "${PIHOLE_HTTP_PORT:-80}:80/tcp"
      - "${PIHOLE_HTTP_PORT:-443}:443/tcp"
