version: '3'
services:
  pihole:
    image: pihole/pihole
    restart: always
    env_file:
      - pihole.env
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "67:67/udp"
      - "8053:80/tcp"
    volumes:
      - pihole_data:/etc/pihole
      - dnsmasq_data:/etc/dnsmasq.d
      - /mnt/space/docker/pihole/pihole.log:/var/log/pihole.log

volumes:
  pihole_data:
  dnsmasq_data:
