version: "3.7"

services:
  flexget:
    image: wiserain/flexget
    restart: unless-stopped
    env_file:
      - flexget.env
    volumes:
      - flexget_data:/data
      - ${FLEXGET_CONFIG_VOLUME:-./config}:/config

volumes:
  flexget_data:
