version: "3.7"

services:
  ps3netsrv:
    image: shawly/ps3netsrv
    restart: unless-stopped
    env_file:
      - ps3netsrv.env
    volumes:
      - ${PS3NETSRV_VOLUME:-games_data}:/games

volumes:
  games_data:
