version: '3'
services:
  cache-steam:
    image: steamcache/generic
    restart: always
    environment:
      CACHE_MEM_SIZE: 500m
      CACHE_DISK_SIZE: 500000m
      CACHE_MAX_AGE: 3650d
    volumes:
      - cache-steam_data:/data/cache
      - cache-steam_logs:/data/logs

volumes:
  cache-steam_data:
  cache-steam_logs:
