version: "3.7"

services:
  db:
    image: postgres:11-alpine
    restart: unless-stopped
    env_file:
      - wikijs.env
    logging:
      driver: "none"
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    depends_on:
      - db

volumes:
  db-data: